### ISSUE TITLE
Question - How much refactoring per contribution would be allowed right now?

### ISSUE THREAD

**Issue by ramonmoraes8080** [containers/podman-py#25]
Hello! Let's get to the point. I just found out that this is the new official repo for the Python's podman lib and it targets the podman v2 which implements a ReST API interface for communications. Assuming that's all correct got a couple of question about contributing on the project:

1 - Is this project aiming to provide compatibility with the other library?

2 - If the answer for [1] is No then: How much code change would you allow at this current time? I notice that we are at the very beginning of the development and notice that we use a lot of functions around one big object (for connection). I would love to rework this using objects to make change on each of those layer easier that will definitively introduce a sort of full refactoring.

**Comment by rhatdan** [comment]
It does not have to match Docker-py, although where there is overlap in function calls, I would not change it for change sake.  I am fine with a major redesign.
@jwhonce @baude WDYT?

**Comment by baude** [comment]
I think help from the community is always welcome. Also, as @rhatdan say, modelling things after docker-py a little bit would seem to help potential migration use cases as well.

**Comment by velvetkeyboard** [comment]
@baude @rhatdan Thanks for the quick reply on this one. I might be able to open a PR with a in deep explanation at Saturday (07/18).

I will try to reserve time to work on compatibility. But would say that: Docker and Podman are two different products. So compatibility would be great but not much of a deal breaker. Correct? To be honest I was more concerned with [python-podman](https://github.com/containers/python-podman) at first, rather then docker itself because my intention is to have a library to work on a compose solution for podman itself.

Yes. I aware of the (podman-compose)[https://github.com/containers/podman-compose] but this one is not even use any of the libraries AFAIK. The plan is to create a stable library here in starting work with it at either the podman-compose or create my own.

**Comment by rhatdan** [comment]
Yes they are separate products and Podman provides a bunch of technology different then Docker. So yes their can be varience, but we have to appreciate programmers coming from dealing with Docker python bindings have developed muscle memory...

**Comment by velvetkeyboard** [comment]
Opened the PR https://github.com/containers/podman-py/pull/26 That should be enough material to give a overview of what's on my mind right now.

@rhatdan Based on this last commented I don't the changes will fit but I'm willing to drop it off and contributing using another design that would allow compatibility.

**Comment by rhatdan** [comment]
@ramonmoraes8080 is this issue still ongoing?

**Comment by ramonmoraes8080** [comment]
@rhatdan Created the PR but got no solid feedback so I moved on to other projects. Not interested in getting back to this issue anytime soon.

**Comment by rhatdan** [comment]
Sorry to hear that.  Thanks for trying.
