### ISSUE TITLE
Centos Stream 9 builds failing

### ISSUE THREAD

**Issue by umohnani8** [containers/podman-py#360]
The centos stream 9 builds are continuously failing on PRs with error that it couldn't find the `rich` package. 

I checked if the version was the problem by removing any version restrictions, but it wasn't the case. Seems like the `rich` package probably doesn't exist on centos stream 9 or it has a very different name.

**Comment by umohnani8** [comment]
@lsm5 can you please look into this when you are back.

**Comment by yselkowitz** [comment]
This affects ELN/c10s as well, due to https://github.com/containers/podman-py/pull/340 having added a hard dependency on `rich`, which has a few new runtime dependencies and collectively have a huge build dependency tree.  At a minimum, please make the dependency (and hence the progress bar functionality) optional (e.g. with a try/except of import rich etc.), or find an alternative implementation which does not introduce so many new dependencies.

**Comment by yselkowitz** [comment]
ping @lsm5
