### ISSUE TITLE
Container is not deleted if detach=True and remove=True are specified

### ISSUE THREAD

**Issue by landgraf** [containers/podman-py#402]
```
remove: Delete container when the container's processes exit. Default: False.

>>> import podman
>>> podman.__version__
'5.0.0'
>>> c = client.containers.run("myimage", detach=True, remove=True, command="/bin/false")
>>> c.status
'exited'

26034e386c92  myimage                                            /bin/false            14 seconds ago     Exited (1) 14 seconds ago              interesting_williamson

```

**Comment by inknos** [comment]
A note:

The following example won't reproduce the issue

```
from podman import PodmanClient

uri = "unix:///run/user/1000/podman/podman.sock"

with PodmanClient(base_url=uri) as client:
    c = client.containers.run("nginx", remove=True, command="/bin/false")

    print(c.status)
```

while 

```
from podman import PodmanClient

uri = "unix:///run/user/1000/podman/podman.sock"

with PodmanClient(base_url=uri) as client:
    c = client.containers.run("nginx", deatch=True, remove=True, command="/bin/false")

    print(c.status)
```

will reproduce

**Comment by inknos** [comment]
Ok, the problem is just that [detach](https://github.com/containers/podman-py/blob/main/podman/domain/containers_run.py#L70-L71) is called before [remove](https://github.com/containers/podman-py/blob/main/podman/domain/containers_run.py#L86-L87). I can see how the options can live together, but since I would avoid delegating the removal to the user or threading/scheduling the removal.

Maybe @jwhonce might have something to add about the reasoning behind the code, or if there were some thoughts already on this detach/remove process.
