### ISSUE TITLE
How to start containers with this module?

### ISSUE THREAD

**Issue by Kaitou786** [containers/podman-py#51]
Hi I have this python module installed and a running socket, I am looking for a way to start a container with this module, similar to the docker.Client(version="1.22").start(some_container). I could find not find the relevant command with this podman module. Any help would be really great :)

**Comment by mwhahaha** [comment]
The code is still pending in #46

**Comment by Kaitou786** [comment]
Ah okay, thanks!

**Comment by mwhahaha** [comment]
Feel free to pull down that version and let me know if it doesn't work in that PR.

**Comment by Kaitou786** [comment]
Okay, will try with that pull :)

**Comment by Kaitou786** [comment]
Is it also possible to add functions like `exec _start` which starts the container with the given command?

**Comment by mwhahaha** [comment]
That doesn't look available via the API. https://docs.podman.io/en/latest/_static/api.html#operation/libpodStartContainer  If you know of a way to do that via the api we should just modify the start container. But that doesn't appear to be possible per the docs.

As for the create command, we don't want to be managing parameter mappings across versions in this module. The goal of this is to be a minimal layer for interaction with the API.  The problem with us having to compose the data, would be that this python module would need to be more version aware and constantly updated if the parameters change. I think it's better for you to do that create data mapping in your application if you only need to customize a few things rather than putting it in this module itself.

**Comment by jwhonce** [comment]
See https://pypi.org/project/podman-py/

```
with podman.PodmanClient() as client:
    image = client.images.pull("quay.io/libpod/alpine", tag="latest")
    container = client.containers.create(image, command=["echo", random_string])
    container.start()
    ....

```
